/**
 * Google Analytics 4 Custom Event Tracking Module.
 *
 * Implements isolated, privacy-compliant event tracking for the staging environment.
 * Incorporates event parameter sanitization, PII redaction, query string cleaning,
 * dynamic section-view telemetry, and click-event delegation tracking.
 *
 * @module analytics
 */

(function () {
  'use strict';

  // 1. Early Google Tag Manager Setup & Privacy Settings
  // Initializing GA4 arrays and objects without inline scripts.
  window.dataLayer = window.dataLayer || [];
  window.gtag = window.gtag || function () {
    window.dataLayer.push(arguments);
  };

  // Only configure tag manager if it hasn't been set up yet
  if (window.dataLayer.length === 0) {
    window.gtag('js', new Date());
    window.gtag('config', 'G-2LC6E9M4Q2', {
      // Disable advertising features to respect privacy in test environment
      allow_google_signals: false,
      allow_ad_personalization_signals: false
    });
  }

  // 2. Telemetry Schema Allowlists
  const ALLOWED_EVENTS = new Set([
    'primary_cta_click',
    'contact_click',
    'navigation_click',
    'theme_change',
    'project_click',
    'section_view',
    'cv_open',
    'recruiter_role_selected'
  ]);

  const ALLOWED_PARAMETERS = new Set([
    'environment',
    'debug_mode',
    'page_path',
    'page_title',
    'destination_section',
    'navigation_location',
    'link_label',
    'control_location',
    'cta_name',
    'cta_location',
    'destination_type',
    'cv_format',
    'link_location',
    'contact_method',
    'contact_location',
    'project_id',
    'project_name',
    'section_id',
    'section_name',
    'selected_theme',
    'cta_label',
    'role'
  ]);

  // 3. Core Verification & Sanitization Helpers

  /**
   * Validates if a given event name is present in the strict event name allowlist.
   *
   * Trust boundary:
   * Event names are internal inputs generated by elements or observers. However, they may 
   * originate from data attributes and are checked to prevent injection of unexpected events.
   *
   * Accepted inputs:
   * String values strictly matching keys in `ALLOWED_EVENTS`.
   *
   * Rejected inputs:
   * Any other event names, non-string values, or special characters.
   *
   * Failure behavior:
   * Returns false. Disables dispatching the event.
   *
   * @param {string} eventName - The name of the telemetry event.
   * @returns {boolean} True if the name is allowed, otherwise false.
   */
  function isValidEventName(eventName) {
    return typeof eventName === 'string' && ALLOWED_EVENTS.has(eventName);
  }

  /**
   * Redacts personally identifiable information (PII) like email and phone numbers,
   * limits string length, strips HTML tags, and removes query strings/hashes from URLs.
   *
   * Trust boundary:
   * String parameter values are read from untrusted DOM elements (data attributes) and
   * must be cleaned before sending them to external analytics systems.
   *
   * Accepted inputs:
   * Any string under 100 characters.
   *
   * Rejected inputs:
   * HTML elements, nested tags, string values exceeding length limits, malformed emails,
   * query strings containing tokens, and URL hashes.
   *
   * Sanitization strategy:
   * Truncates value to 100 chars, strips HTML markup with regex, applies regex redactions 
   * for emails and phone numbers, and parses/cleans URLs using the native URL parser.
   *
   * DOM sink avoided:
   * Prevents persistent XSS injections in Google Analytics reporting consoles (log injection).
   *
   * Privacy implications:
   * High. Prevents leakage of user email addresses, phone numbers, and URL query credentials.
   *
   * @param {string} val - The raw parameter value to clean.
   * @returns {string} The redacted and sanitized string value.
   */
  function sanitizeAnalyticsValue(val) {
    if (typeof val !== 'string') return '';

    // Limit maximum length to prevent overflow/injection payloads
    let sanitized = val.substring(0, 100).trim();

    // Strip HTML tags to avoid DOM-XSS log injection
    sanitized = sanitized.replace(/<[^>]*>/g, '');

    const emailRegex = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;
    const phoneRegex = /(\+?\d{1,4}[-.\s]??)?(\(?\d{3}\)?[-.\s]??\d{3}[-.\s]??\d{4})/g;

    // Redact email patterns
    sanitized = sanitized.replace(emailRegex, '[REDACTED_EMAIL]');
    // Redact phone patterns
    sanitized = sanitized.replace(phoneRegex, '[REDACTED_PHONE]');

    // Remove query parameters and hashes from URLs
    if (sanitized.includes('://') || sanitized.startsWith('/') || sanitized.startsWith('.')) {
      try {
        const base = sanitized.startsWith('/') || sanitized.startsWith('.') ? window.location.origin : undefined;
        const urlObj = new URL(sanitized, base);
        if (urlObj.search || urlObj.hash) {
          urlObj.search = '';
          urlObj.hash = '';
          sanitized = sanitized.startsWith('/') || sanitized.startsWith('.')
            ? urlObj.pathname
            : urlObj.toString();
        }
      } catch (e) {
        // Ignore URL parsing errors and keep string as-is
      }
    }

    return sanitized;
  }

  /**
   * Sanitizes all properties in the event parameters object.
   * Filters out nested structures, discards unknown parameter names, and sanitizes values.
   *
   * Trust boundary:
   * Object keys and values are read from untrusted DOM elements (data attributes).
   *
   * Accepted inputs:
   * Flattened objects containing only parameters matching `ALLOWED_PARAMETERS`.
   *
   * Rejected inputs:
   * Discards keys not defined in `ALLOWED_PARAMETERS`, arrays, nested objects, and functions.
   *
   * Sanitization strategy:
   * Loops through keys, discards unauthorized attributes, flattens type-coerced values, 
   * and runs primitive validation rules on string/number/boolean inputs.
   *
   * @param {Object} parameters - Raw parameters dictionary.
   * @returns {Object} A flat, sanitized parameters dictionary.
   */
  function sanitizeAnalyticsParameters(parameters) {
    const eventParams = {};
    if (!parameters || typeof parameters !== 'object') return eventParams;

    for (const key in parameters) {
      if (Object.prototype.hasOwnProperty.call(parameters, key)) {
        // 1. Validate parameter name against allowlist
        if (!ALLOWED_PARAMETERS.has(key)) {
          console.warn(`[Analytics] Discarded disallowed parameter key: "${key}"`);
          continue;
        }

        const value = parameters[key];

        // 2. Drop nested structures (objects/arrays)
        if (value !== null && typeof value === 'object') {
          console.warn(`[Analytics] Nested parameter object not allowed for key: "${key}"`);
          continue;
        }

        // 3. Sanitize primitive values based on expected type and format
        if (typeof value === 'string') {
          eventParams[key] = sanitizeAnalyticsValue(value);
        } else if (typeof value === 'boolean') {
          eventParams[key] = value;
        } else if (typeof value === 'number') {
          eventParams[key] = Number.isFinite(value) ? value : 0;
        } else {
          // Coerce any other values to string and sanitize
          eventParams[key] = sanitizeAnalyticsValue(String(value));
        }
      }
    }

    return eventParams;
  }

  /**
   * Detects the current execution path and generates staging/environment metadata parameters.
   *
   * Privacy implications:
   * Identifies staging actions explicitly to prevent contamination of production metrics.
   *
   * @returns {Object} Staging telemetry metadata parameters.
   */
  function getCurrentEnvironmentParameters() {
    const params = {};
    const isTest = window.location.pathname.startsWith('/test');
    if (isTest) {
      params.environment = 'test';
      params.debug_mode = true;
    }
    return params;
  }

  // 4. Public Tracking Interface

  /**
   * Dispatches a custom GA4 telemetry event safely.
   *
   * Security boundary:
   * Accepts event name and arguments from various modules. Runs schemas validation before 
   * routing data to global site tag API.
   *
   * Failure behavior:
   * Safe. If `window.gtag` is unavailable or if event validation fails, the event is logged
   * to the console in staging and the function fails silently without blocking user actions.
   *
   * CSP dependency:
   * Connects to `https://www.google-analytics.com` and `https://*.google-analytics.com`.
   *
   * @global
   * @param {string} eventName - Lowercase snake_case identifier for the GA4 event.
   * @param {Object} [parameters={}] - Key-value pair parameters containing event metadata.
   * @returns {void}
   */
  window.trackAnalyticsEvent = function (eventName, parameters) {
    if (typeof window.gtag !== 'function') {
      const isTest = window.location.pathname.startsWith('/test');
      if (isTest) {
        const devParams = Object.assign(
          getCurrentEnvironmentParameters(),
          { page_path: window.location.pathname, page_title: document.title },
          sanitizeAnalyticsParameters(parameters)
        );
        console.log(`[Analytics Event (gtag offline)] "${eventName}"`, devParams);
      }
      return;
    }

    try {
      if (!isValidEventName(eventName)) {
        console.warn(`[Analytics] Disallowed event name discarded: "${eventName}".`);
        return;
      }

      const eventParams = Object.assign(
        {
          page_path: window.location.pathname,
          page_title: document.title
        },
        getCurrentEnvironmentParameters(),
        sanitizeAnalyticsParameters(parameters)
      );

      const isTest = window.location.pathname.startsWith('/test');
      if (isTest) {
        console.log(`[Analytics Event] "${eventName}"`, eventParams);
      }

      window.gtag('event', eventName, eventParams);

    } catch (error) {
      console.error('[Analytics] Error sending event:', error);
    }
  };

  // 5. Dynamic DOM Event Handlers

  /**
   * Scrapes metadata attributes formatting `data-analytics-param-*` from an element.
   *
   * @param {HTMLElement} element - The DOM element containing attributes.
   * @returns {Object} Extracted key-value pair parameters.
   */
  function collectAnalyticsDataAttributes(element) {
    const params = {};
    if (!element || !element.attributes) return params;

    Array.from(element.attributes).forEach(attr => {
      if (attr.name.startsWith('data-analytics-param-')) {
        const paramName = attr.name.substring('data-analytics-param-'.length).replace(/-/g, '_');
        params[paramName] = attr.value;
      }
    });

    return params;
  }

  /**
   * Establishes a delegated click listener on the document root.
   */
  function initializeAnalyticsClickTracking() {
    document.addEventListener('click', function (event) {
      const trackableEl = event.target.closest('[data-analytics-event]');
      if (!trackableEl) {
        return;
      }

      const eventName = trackableEl.getAttribute('data-analytics-event');
      if (!eventName) return;

      const params = collectAnalyticsDataAttributes(trackableEl);

      // Special handling for theme_change (wait for class list update)
      if (eventName === 'theme_change') {
        setTimeout(() => {
          const isDark = document.documentElement.classList.contains('dark');
          params.selected_theme = isDark ? 'dark' : 'light';
          window.trackAnalyticsEvent(eventName, params);
        }, 0);
      } else {
        window.trackAnalyticsEvent(eventName, params);
      }
    });
  }

  /**
   * Initializes visibility trackers on portfolio sections using IntersectionObserver.
   */
  function initializeSectionViewTracking() {
    if (typeof IntersectionObserver !== 'function') {
      return;
    }

    const trackedSections = new Set();
    const visibilityTimers = new Map();

    const observerOptions = {
      root: null,
      threshold: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        const id = entry.target.id;
        const name = entry.target.getAttribute('data-analytics-section') || id;

        if (trackedSections.has(id)) {
          return;
        }

        const visibleHeight = entry.intersectionRect.height;
        const elementHeight = entry.boundingClientRect.height;
        const viewportHeight = window.innerHeight;

        const is50PercentVisible = entry.intersectionRatio >= 0.5 ||
          (elementHeight > viewportHeight && visibleHeight >= viewportHeight * 0.5);

        if (is50PercentVisible) {
          if (!visibilityTimers.has(id)) {
            const timer = setTimeout(() => {
              window.trackAnalyticsEvent('section_view', {
                section_id: id,
                section_name: name
              });
              trackedSections.add(id);
              observer.unobserve(entry.target);
              visibilityTimers.delete(id);
            }, 1000);
            visibilityTimers.set(id, timer);
          }
        } else {
          if (visibilityTimers.has(id)) {
            clearTimeout(visibilityTimers.get(id));
            visibilityTimers.delete(id);
          }
        }
      });
    }, observerOptions);

    document.querySelectorAll('[data-analytics-section]').forEach(sec => {
      observer.observe(sec);
    });
  }

  /**
   * Detects visits to the Curriculum Vitae section and dispatches attribution metadata.
   */
  function initializeCvTracking() {
    if (window.location.pathname.includes('/cv/')) {
      let linkLocation = 'direct';
      if (document.referrer) {
        try {
          const refUrl = new URL(document.referrer);
          if (refUrl.hostname === window.location.hostname) {
            linkLocation = refUrl.pathname;
          } else {
            linkLocation = 'external';
          }
        } catch (e) {
          linkLocation = 'unknown';
        }
      }
      window.trackAnalyticsEvent('cv_open', {
        cv_format: 'html',
        link_location: linkLocation
      });
    }
  }

  // 6. Registration bootstrap
  initializeAnalyticsClickTracking();

  document.addEventListener('DOMContentLoaded', function () {
    initializeSectionViewTracking();
    initializeCvTracking();
  });

})();
